### PR TITLE
breaking(plugin): Make `publish` generic over Message and not Message data

### PR DESCRIPTION
**Pull request by Steven0351**
This should allow for doing things like this:
```typescript
type Messages = 
  | { topic: "cart:dismiss", data: "clear" | "cancel" }
  | { topic: "user:delete", data: User }

publish<Messages>({ topic: "cart:dismiss", data: "cancel" }) //totally fine
publish({ topic: "something:else", data: 1 }) // totally fine
publish<Messages>({ topic: "user:delete", data: "clear" }) // typescript error
publish<Messages>({ topic: "something:else", data: 1 }) // typescript error
```

Props to @eric-horodyski for the idea

### CODE REVIEW

**Review by eric-horodyski — APPROVED** [review]
LGTM

**Review by carlpoole — APPROVED** [review]
nice!

**Comment by eric-horodyski** [comment]
Any idea when a release will be cut for this? Would like to communicate to customers and bump up demo project

**Comment by Steven0351** [comment]
We could cut it at any time. Maybe today? We don't really have a regular release cadence for the projects so there is no tempo we usually go off of.

**Comment by eric-horodyski** [comment]
@Steven0351 - Let me create a PR for doc updates and once it's merged we can publish?

**Comment by Steven0351** [comment]
Sounds good to me

**Pull request merged**
